### ISSUE TITLE
dat in tbl function cannot get values from list x which has no value in it.

### ISSUE THREAD

**Issue by lidingruc** [huashan/ezdf#1]
> library(ezdf)
> dat = readStata('CGSS2013p.dta', encoding = 'GB2312')
> tbl(dat, a66 ~ s5a)
> Error in x[j] : invalid subscript type 'list'
> Called from: `[.data.frame`(x, i, j)

dat in tbl function cannot get values from list x which has no value in it.
maybe something wrong in ez.r line 180 181 
      #dat = dt[!is.na(eval(parse(text=grp))), eval(expr), by = eval(parse(text = sprintf('list(%s)', x))), .SDcols = vars]
      dat = ez[!is.na(eval(parse(text=grp))), eval(expr), by = eval(parse(text =grp)), .SDcols = vars]

**Comment by huashan** [comment]
fixed in https://github.com/huashan/ezdf/commit/1d01d47d7fffcf1b67bb37870fb5454ec542b591
